### ISSUE TITLE
Tracing not active

### ISSUE THREAD

**Issue by mabakach** [DP-3T/dp3t-app-ios#11]
The current version of NextStep from TestFlight showed today that tracing is not active. Bluetooth was active and tracing was activated the day before and not manually deactivated afterwards. After switching to the NextStep app again, tracing was active again.

![TracingNotActive](https://user-images.githubusercontent.com/8707292/79697189-962ac980-8281-11ea-852d-d09a9eed0f8c.PNG)
![SettingsBluetoothEnabled](https://user-images.githubusercontent.com/8707292/79697184-932fd900-8281-11ea-9451-1238d57f3986.PNG)

**Comment by codebarista** [comment]
I also had this issue after automatically switching off the power saving mode while charging. In the power saving mode, the app background updates are disabled and bluetooth in flight mode. Maybe it just took too long overnight to use the mobile phone and the app again.

**Comment by uomogrande** [comment]
i noticed the same behavior when there was no internet connection during startup of the app

**Comment by matteocef** [comment]
Same here. iPhone 7 plus, last iOS.

**Comment by Trevzn** [comment]
Same here, tried to:
- re-install Next Step
- shutting down Tracing, BT and permission to BT for Next Step, then switching on everything again 

Next 2 do : shutting down the iPhone and retry

**Comment by Trevzn** [comment]
Switched off the iPhone X, tracing still not active.

![D2EA0238-2E7C-4F3C-84FA-1AA11E2918C7](https://user-images.githubusercontent.com/32069207/80189280-b86e6f80-8612-11ea-831b-7ea5b4429e3f.png)
![7B974094-470C-438A-A8E6-346463D35949](https://user-images.githubusercontent.com/32069207/80189286-b99f9c80-8612-11ea-9a92-ff4f56d968fe.png)

**Comment by flospi** [comment]
Same problem here. Tried deactivating and activating Bluetooth and restarted the phone.

**Comment by pelinquin** [comment]
same for me on iOs and also on Android !

**Comment by matteocef** [comment]
Maybe in this part of the beta, the tracking is not active at all?

**Comment by krzakala** [comment]
Same here. is it a bug or a problem with a recent Apple update ?

**Comment by fabtho** [comment]
A similar bug on android, so maybe this is not related to the OS :

https://github.com/DP-3T/dp3t-app-android/issues/38

**Comment by msireau** [comment]
Same for me too : iPhone 7, iOS 13.3

**Comment by rogerfischer** [comment]
Same here for me too: iPhone 7, 13.3.1

**Comment by maerki** [comment]
Please have a look at https://github.com/DP-3T/dp3t-app-ios-ch to see a complete working app, which we developed for CH. The example app has not been updated yet to fix this issue.

**Comment by rogerfischer** [comment]
@maerki Is it possible to download the new app via Testflight too? 

Or is this the only way for now?
https://github.com/DP-3T/dp3t-app-ios-ch#installation-and-building

**Comment by maerki** [comment]
This was implemented on the CH-specific branch and merged back with the latest commit.

@rogerfischer We currrently don't have a version on TestFlight, please build the CH-app or the demo project yourself if you need to test.
