### ISSUE TITLE
Problem with Reports screen

### ISSUE THREAD

**Issue by JLRaisaro** [DP-3T/dp3t-app-ios#19]
In the Reports screen, after scrolling down the text, the two paragraphs keeps repeating several times.
![FDC84FB1-773E-49A9-BE82-088F19B6F5EB](https://user-images.githubusercontent.com/24383576/80033459-1143e800-84ed-11ea-9ed4-75e853b2070d.png)

**Comment by maerki** [comment]
Please have a look at https://github.com/DP-3T/dp3t-app-ios-ch to see a complete working app, which we developed for CH. The example app has not been updated yet to fix this issue.

**Comment by maerki** [comment]
This was implemented on the CH-specific branch and merged back with the latest commit.
