### ISSUE TITLE
Testing not possible in Test Flight

### ISSUE THREAD

**Issue by stefanbuttigieg** [DP-3T/dp3t-app-ios#24]
I was informed in Test Flight that no more beta testers are accepted. Any reason why?

**Comment by vistalba** [comment]
Had already installed earlier beta. Got message that this build was removed. So I deleted the build. Now I also get the message that I can‘t get new beta build woth the provided link.

**Comment by maerki** [comment]
The TestFlight version is more than outdated and was therefore removed.
