### ISSUE TITLE
Problematic Class Prefix?

### ISSUE THREAD

**Issue by mangerlahn** [DP-3T/dp3t-app-ios#7]
Since the project is called "Next Step", the NS class prefix seems like an intuitive choice. However this prefix is also used by Apple itself throughout the Foundation framework.

Having classes with the same name is problematic, especially if Objective-C code has to be integrated in any form into this project. 
Since name spaces exist in Swift, this is not an immediate problem, but still, it _could_ become a problem. 
I found it also quite confusing to find custom NS* classes in the project, as this prefix is basically reserved for Apple's classes. There is even a class that is called `NSDateFormatter`, a class that actually exists in Foundation. 

I suggest using the UB prefix on all classes throughout the project, or remove the prefix altogether.

Happy to hear your thoughts on this.

**Comment by mangerlahn** [comment]
Another thing worth discussing is the mix of German and English language in the code. It would probably be better to unify this to use an all-english code base.

**Comment by darthpelo** [comment]
Agree with you @mangerlahn will be better to move all the comment to English.
Since this application is more an example about how to use the DP-3T SDK, I will propose `DP` as the prefix, but only for Objective-C class, since in Swift there is no sense to use the prefix.

**Comment by roddi** [comment]
Fun Fact / Trivia:

Before Foundation was a part of iOS it was a part of macOS/OS X and still is, before Apple bought NeXT in '97 it was part of OpenStep and before that a part of NeXTStep. So it's your guess what Apple's NS* prefix actually stands for…

**Comment by roddi** [comment]
Two more things actually connected to the problem at hand:
1. Prefixes are only used in Objective C
2. Apple reserves two letter prefixes for themselves, so you should use three letters for app code and four letters for framework code. 

I would say use either UBQ or NXS as a prefix if you really think you must use one.

**Comment by maerki** [comment]
This was implemented on the CH-specific branch and merged back with the latest commit.
